/*
Copyright (c) 2019-2023 Timur Gafarov.

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module bindbc.wgpu.types2;

import bindbc.wgpu.types;

/*
 * Type definitions from wgpu.h
 */

enum WGPUNativeSType
{
    // Start at 6 to prevent collisions with webgpu STypes
    DeviceExtras = 0x00030001,
    RequiredLimitsExtras = 0x00030002,
    PipelineLayoutExtras = 0x00030003,
    ShaderModuleGLSLDescriptor = 0x00030004,
    SupportedLimitsExtras = 0x00030005,
    InstanceExtras = 0x00030006,
    BindGroupEntryExtras = 0x00030007,
    BindGroupLayoutEntryExtras = 0x00030008,
    Force32 = 0x7FFFFFFF
}

enum WGPUNativeFeature
{
    PushConstants = 0x00030001,
    TextureAdapterSpecificFormatFeatures = 0x00030002,
    MultiDrawIndirect = 0x00030003,
    MultiDrawIndirectCount = 0x00030004,
    VertexWritableStorage = 0x00030005,
    TextureBindingArray = 0x00030006,
    SampledTextureAndStorageBufferArrayNonUniformIndexing = 0x00030007,
    Force32 = 0x7FFFFFFF
}

enum WGPULogLevel
{
    Off = 0x00000000,
    Error = 0x00000001,
    Warn = 0x00000002,
    Info = 0x00000003,
    Debug = 0x00000004,
    Trace = 0x00000005,
    Force32 = 0x7FFFFFFF
}

enum WGPUInstanceBackend
{
    All = 0x00000000,
    Vulkan = 1 << 0,
    GL = 1 << 1,
    Metal = 1 << 2,
    DX12 = 1 << 3,
    DX11 = 1 << 4,
    BrowserWebGPU = 1 << 5,
    Primary = Vulkan | Metal | DX12 | BrowserWebGPU,
    Secondary = GL | DX11,
    Force32 = 0x7FFFFFFF
}

alias WGPUInstanceBackendFlags = WGPUFlags;

enum WGPUInstanceFlag 
{
    Default = 0x00000000,
    Debug = 1 << 0,
    Validation = 1 << 1,
    DiscardHalLabels = 1 << 2,
    Force32 = 0x7FFFFFFF
}

alias WGPUInstanceFlags = WGPUFlags;

enum WGPUDx12Compiler
{
    Undefined = 0x00000000,
    Fxc = 0x00000001,
    Dxc = 0x00000002,
    Force32 = 0x7FFFFFFF
}

enum WGPUGles3MinorVersion {
    Automatic = 0x00000000,
    Version0 = 0x00000001,
    Version1 = 0x00000002,
    Version2 = 0x00000003,
    Force32 = 0x7FFFFFFF
}

struct WGPUInstanceExtras
{
    WGPUChainedStruct chain;
    WGPUInstanceBackendFlags backends;
    WGPUInstanceFlags flags;
    WGPUDx12Compiler dx12ShaderCompiler;
    WGPUGles3MinorVersion gles3MinorVersion;
    const char * dxilPath;
    const char * dxcPath;
}

struct WGPUDeviceExtras
{
    WGPUChainedStruct chain;
    const(char)* tracePath;
}

struct WGPUNativeLimits {
    uint maxPushConstantSize;
    uint maxNonSamplerBindings;
}

struct WGPURequiredLimitsExtras
{
    WGPUChainedStruct chain;
    WGPUNativeLimits limits;
}

struct WGPUSupportedLimitsExtras
{
    WGPUChainedStructOut chain;
    WGPUNativeLimits limits;
}

struct WGPUPushConstantRange
{
    alias WGPUShaderStageFlags = uint;
    WGPUShaderStageFlags stages;
    uint start;
    uint end;
}

struct WGPUPipelineLayoutExtras
{
    WGPUChainedStruct chain;
    uint pushConstantRangeCount;
    WGPUPushConstantRange* pushConstantRanges;
}

alias WGPUSubmissionIndex = ulong;

struct WGPUWrappedSubmissionIndex
{
    WGPUQueue queue;
    WGPUSubmissionIndex submissionIndex;
}

struct WGPUShaderDefine
{
    const(char)* name;
    const(char)* value;
}

struct WGPUShaderModuleGLSLDescriptor
{
    WGPUChainedStruct chain;
    WGPUShaderStage stage;
    const(char)* code;
    uint defineCount;
    WGPUShaderDefine* defines;
}

struct WGPUStorageReport
{
    size_t numOccupied;
    size_t numVacant;
    size_t numError;
    size_t elementSize;
}

struct WGPUHubReport
{
    WGPUStorageReport adapters;
    WGPUStorageReport devices;
    WGPUStorageReport pipelineLayouts;
    WGPUStorageReport shaderModules;
    WGPUStorageReport bindGroupLayouts;
    WGPUStorageReport bindGroups;
    WGPUStorageReport commandBuffers;
    WGPUStorageReport renderBundles;
    WGPUStorageReport renderPipelines;
    WGPUStorageReport computePipelines;
    WGPUStorageReport querySets;
    WGPUStorageReport buffers;
    WGPUStorageReport textures;
    WGPUStorageReport textureViews;
    WGPUStorageReport samplers;
}

struct WGPUGlobalReport
{
    WGPUStorageReport surfaces;
    WGPUBackendType backendType;
    WGPUHubReport vulkan;
    WGPUHubReport metal;
    WGPUHubReport dx12;
    WGPUHubReport dx11;
    WGPUHubReport gl;
}

struct WGPUInstanceEnumerateAdapterOptions
{
    const(WGPUChainedStruct)* nextInChain;
    WGPUInstanceBackendFlags backends;
}

struct WGPUBindGroupEntryExtras
{
    WGPUChainedStruct chain;
    const(WGPUBuffer)* buffers;
    size_t bufferCount;
    const(WGPUSampler)* samplers;
    size_t samplerCount;
    const(WGPUTextureView)* textureViews;
    size_t textureViewCount;
}

struct WGPUBindGroupLayoutEntryExtras
{
    WGPUChainedStruct chain;
    uint count;
}

extern(C):

alias WGPULogCallback = void function (WGPULogLevel level, const(char)* message, void* userdata);

extern(C) @nogc nothrow:

alias WGPUProcGenerateReport = void function(WGPUInstance instance, WGPUGlobalReport* report);
alias WGPUProcInstanceEnumerateAdapters = size_t function(WGPUInstance instance, const(WGPUInstanceEnumerateAdapterOptions)* options, WGPUAdapter* adapters);

alias WGPUProcQueueSubmitForIndex = WGPUSubmissionIndex function(WGPUQueue queue, size_t commandCount, const(WGPUCommandBuffer)* commands);

// Returns true if the queue is empty, or false if there are more queue submissions still in flight.
alias WGPUProcDevicePoll = WGPUBool function(WGPUDevice device, WGPUBool wait, const(WGPUWrappedSubmissionIndex)* wrappedSubmissionIndex);

alias WGPUProcSetLogCallback = void function(WGPULogCallback callback, void* userdata);

alias WGPUProcSetLogLevel = void function(WGPULogLevel level);

alias WGPUProcGetVersion = uint function();

alias WGPUProcRenderPassEncoderSetPushConstants = void function(WGPURenderPassEncoder encoder, WGPUShaderStageFlags stages, uint offset, uint sizeBytes, const(void)* data);

alias WGPUProcRenderPassEncoderMultiDrawIndirect = void function(WGPURenderPassEncoder encoder, WGPUBuffer buffer, ulong offset, uint count);
alias WGPUProcRenderPassEncoderMultiDrawIndexedIndirect = void function(WGPURenderPassEncoder encoder, WGPUBuffer buffer, ulong offset, uint count);

alias WGPUProcRenderPassEncoderMultiDrawIndirectCount = void function(WGPURenderPassEncoder encoder, WGPUBuffer buffer, ulong offset, WGPUBuffer count_buffer, ulong count_buffer_offset, uint max_count);
alias WGPUProcRenderPassEncoderMultiDrawIndexedIndirectCount = void function(WGPURenderPassEncoder encoder, WGPUBuffer buffer, ulong offset, WGPUBuffer count_buffer, ulong count_buffer_offset, uint max_count);
